version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres_db
    ports:
      - 8080:8080
